const sourceTitle =
  'The Twenty-Seven Enneagram Type and Instinctual Type Combinations';
const source =
  'https://www.johnluckovich.com/articles/the-twenty-seven-enneagram-type-and-instinctual-type-combinations';
const buyBook =
  'https://read.amazon.com/kp/embed?asin=B09DK64TDC&preview=newtab&linkCode=kpe&ref_=cm_sw_r_kb_dp_FHWA05C62DSTJX1Z2KY2';

const types = new Map();
types.set('8', {
  core: [
    'In Type Eight, the Essential Quality of Power collapses into the Passion of Lust. The drive to experience the immediacy and fullness of the moment leads to chronic exertion and forcing when unable to receive impressions of Essence. Thus, Type Eight applies force when trying to meet the needs of their Dominant Instinct.',
  ],
  sp: [
    'Self-Preservation Eights tend to be excessive and forceful in the pursuit of what they believe supports physical well-being. This amounts to an excessive preoccupation with autonomy. They do not want to have to answer to others, and they aim to be self-reliant above all.',
    'Self-Preservation Eights spend a great deal of energy trying to make money or to find a "sure thing" in terms of a desired lifestyle, even if they were already born into privilege. There can be an attitude of "getting mine," with a propensity to see others’ success and well-being as a threat or affront to their own. They can become controlling about their resources and fight off any perceived attempt to wield any influence over them, even to the point of seeing any form of compromise with others as a personal infringement. Fixated Self-Preservation Eights push hard for their desired vision of autonomy and prosperity, but often at great cost to their relationships and physical and emotional health. They’re likely to regularly provoke power struggles and conflict related to carving out their own way of life. This may mean pushing up against others in business dealings, competition, athletics, or acquisitions, treating life as a battle or game.',
    'For all the intensity typically displayed in Eights, they’re actually pushing up against an inner sense of deadening, a lack of being touched by their experience, so the more entranced a Self-Preservation Eight, the less they’re able to directly register impressions of well-being. This results in being so caught up in self-assertion and struggle that they become physically neglectful or even reckless about their own well-being.',
  ],
  sx: [
    'Sexual Eights can be excessively forceful in capturing the interest of the object of their desire. They put a great deal of effort toward amplifying their impact on the object of desire from the assumption that fully capturing their beloved’s attention is the way to ensure that attraction is on their terms. While Self-Preservation Eights have very solid boundaries and Social Eights tend to hold a strong social “field,” Sexual Eights have a more permeable boundary because of the Sexual Drive’s responsiveness to chemistry and disposition of relenting to attraction. It gives the usual charisma of Eights a hint of self-consciousness and adds receptivity to chemistry, which is shared with only a select few.',
    'As much as Sexual Eights want to “hook” someone, a fear of rejection or of being controlled by their own desire can motivate this Instinctual Type to provocatively invite rejection or disinterest, or to preemptively end relationships in order to make sure rejection is under their control.  Sexual Eights avoid feeling rejection or a lack of reciprocated attraction on the basis of traits and qualities close to their hearts, so they often make a big display of being too much to handle, an “excuse” with which they can easily write off their failure to gain the interest they’re looking for. When in a relationship, Sexual Eights have a propensity to ongoingly provoke reactions from a partner in order to feel connected in place of authentic relating. Control, domination, possessiveness, entitlement, and testing their romantic interest’s time and emotional and physical “tolerance” are common in entranced Sexual Eights.',
  ],
  so: [
    'Social Eights are looking for the experience of Essential Power through relationships and having a strong influence on other people. Social Eights tend to have immense energy for other people and tend to be the most personable, approachable Eights. They are classic protectors and find fulfillment in mentoring, advocating for others, and helping others find their own power.',
    'Social Eights want to make a big splash within their community, to impact friends and family alike. This desire can be harnessed positively or negatively, for being of service to others or for megalomaniacal fantasies, control, manipulation underpinned by a sense of entitlement to others’ respect and attention.',
    'Social Eights stave off fears of abandonment and ostracization by being the instigating centerpiece or ringleader that provides their group, organization, family, or friends a sense of meaning or mission. They often set agendas for others for the purpose of keeping people together, which results in them becoming de facto leaders. However, they will unconsciously assume others are rejecting them with the same ferocity they are rejecting their own vulnerability, and in place of being able to maintain relationships on the basis of personal connection, they will use provocation, stirring up drama, and forcing their way into others lives as a way to remain on others social radar.',
  ],
});

types.set('9', {
  core: [
    'In Type Nine, the Essential Quality of Harmony collapses into the Passion of Sloth. The longing to experience the coherent, syncretic quality of the present leads to self-fragmentation and dissociation. Therefore, Type Nines use instinctual resources to self-forget, either by distracting themselves from individuating or using instinctual resources as a means to self-narcotize, failing to develop themselves beyond the minimum needed to maintain instinctual needs.',
  ],
  sp: [
    'Self-Preservation Nines are looking to experience Essential Harmony through their lifestyle and interests. Self-Preservation Nines are the most independent style of Nine.',
    'Nines dominant in Self-Preservation will typically seek out lifestyles that provide enough independence that they don’t have to be answerable to or at the whim of other people’s agendas. This can mean keeping them in a kind of outward-focused busyness or an immobile slump that distracts them from fully seeing their present circumstances. There is a way in which they also “settle,” not quite going for what they really want to the extent they could and instead contenting themselves with lifestyles and desires that don’t require them to reach too far outside a limited comfort zone. They may view “getting by on a little” as humble or even virtuous and may seek to keep their “world small.”',
    'Self-Preservation Nines are stubbornly entrenched in their habits and routines, so they put a great deal of energy into making sure too much isn’t demanded from them. Despite a reputation for being self-effacing and low-key, when certain boundaries are infringed on or demands placed on them, they can react with intense aggression.',
    'Young Self-Preservation Nines are prone to having a difficult time in knowing what path or direction they want to take through adulthood, and they will delay choosing something definite for a great deal of time. They can be late bloomers in all areas of life, taking a long time to complete their studies or acquire certain skills. Following a path laid out to them by others, or sticking with an unrewarding job while making sure to look busy, are strategies of putting on a performance to parents and loved ones, appearing to be proactively reaching for a goal without taking any real steps. The struggle here is not that Self-Preservation Nines don’t have interests or talents, but they often easily give up on themselves.',
    'Ironically, Self-Preservation Nines have some of the greatest potential for endurance of all the Enneagram Types, so once they have an aim they can get their energy behind, they typically achieve that aim and are not easily dissuaded nor taken off track. The difficulty comes in really pulling their energy out of distractions and into something that will enliven and challenge them.',
  ],
  sx: [
    'Sexual Nines are looking to experience Essential Harmony through chemistry and sexual relationships, and their attraction style tends to be more focused on inviting attraction rather than outright pursuit. Sexual Nines have a flirtatious style that balances an edginess with reassuring sweetness. The imaginative quality of this type can lend itself to a great deal of creativity or idealism, but this can suffer from a lack of grounding.',
    'Sexual Nines know how to temper the aggressive edges of the Sexual Drive with attunement more skillfully than other Sexual Types. The good-natured quality of Nine supports people in feeling relaxed and comfortable in letting their guard down.',
    'Despite usually being attractive, however, Sexual Nines can struggle with feeling overlooked, unseen, or unwanted. Sexual Nines are typically confident in their physical appearance, but they suffer when they feel elements of their personality are unacceptable or uninteresting, or when they simply can’t “find themselves.” They can feel they disappear beneath their sexual display or that they aren’t wanted unless they’re attractive.',
    'People of this type will put pressure on themselves to attract yet may come to feel resentful toward their partner for having compromised their own autonomy in order to remain alluring. This can lead them to either spacing out—hiding something of themselves from their partner so they can’t fully “give themselves away”—or mysteriously breaking off the relationship because they’ve felt they couldn’t really be themselves. As an expression of Sloth, Sexual Nines may settle for a partner who may not value them or support their growth. When a Sexual Nine is very unhealthy, they may have a manipulative side, using their desirability and sexuality to get by in life at the expense of really developing themselves. Their sexuality can be dissociated, “leaking” inappropriately, and they can give themselves to partners who don’t value and respect them.',
  ],
  so: [
    'Social Nines are seeking to experience Essential Harmony through their relationships and their contributions to others. Social Nines tend to be the most outgoing, friendly, and charismatic Nines. Social Nines tend to be actively involved with other people, and despite their modesty, they often make a big impact. They can easily fall into a kind of caretaker or “therapist” role with others. Deeply supportive and self-effacing, Social Nines can feel taken for granted since they care for friends and loved ones and don’t ask much in return.',
    "For Social Nines, autonomy conflicts can take shape as a tension between how much they give themselves over to relationships versus how much they keep for themselves. This can play out in Nines as compartmentalizing different aspects of themselves that get expressed in different relationships. They can be outwardly the most malleable Nine, while covertly keeping others at arm's length. It means that the Social Nine stays dispersed and divided, both connected to and outside of relationships at the same time. They allow much of their personal self-expression to be determined more by the perceived needs of the relationship than from fully showing up as their whole self.",
    'Sloth can manifest in Social Nine as preemptive self-rejection of their own gifts. They can hide their capacities, talents, and individuality in order to remain accepted by others. A conflict can emerge for people of this type in both wanting attention and recognition while also feeling that being too singled out is narcissistic or threatens the respect and connections they have with others. This can create a great deal of tension and inner resistance, leading to resentment, and in some cases, passive aggressive behaviors and occasional eruptions of anger.',
    'The checked-out Social Nine may then rationalize they’re looking for a better relationship or better social conditions to more fully express themselves, but this fantasy is often a way to simply delay showing up in the present. Likewise, the flipside is that they may settle with certain friends and relationships that don’t have their best interests at heart or who encourage them to remain in limited identities.',
  ],
});

types.set('1', {
  core: [
    'In Type One, the Essential Quality of Integrity collapses into the Passion of Anger. The drive to experience the aligned, sacred quality of the present leads to frustration and judgment. Type One critiques their own instinctual needs and resources as a way of controlling ego-boundaries, thereby feeling separate from the objects of their critique.',
  ],
  sp: [
    'Self-Preservation Ones seek to experience Essential Integrity through their lifestyle and well-being, and they put a great deal of energy into determining the best way to live in accordance with their values. For them, living with integrity means making sure the choices they make correspond to principles of good. Every area of life is intentionally considered: the right diet, work, hygiene, and even how the day is structured and how time is spent, because creating coherence between their personal values and how they are expressed in micro and macro details help the Self-Preservation One find clarity, orientation, and purpose.',
    'Many Self-Preservation Ones can exhibit a great deal of anxiety around lifestyle choices. Their home, for example, is often the object of emotional fuss. Contrary to stereotypes, it’s not always the case that Self-Preservation Ones’ living spaces are perfectly tidied and ordered, but there is almost always some clear intentionality. It might be aesthetically “just right,” it might represent an ideal environment for caring for a family, or it might be an expression of a particular kind of lifestyle.',
    'Self-Preservation Ones are also typically quite frugal and have strong boundaries around money and can be surprisingly intense about territory and having control over their sense of autonomy. They can emphasize correct procedures and correct habits, in themselves and in others. For distressed Self-Preservation Ones, there is little room for disruptions or flexibility outside narrow parameters. Therefore, punitive self-control can be met with “leaks” whereby the One tries to release some of the pressure built up around their harsh inner critic, such as being extremely choosy around their diet and then binging on sugar after a lengthy period of “good behavior.”',
    'In attempting to avoid feelings of being flawed, the imbalanced Self-Preservation One will feel a need to justify the correctness of their lifestyle, leading to some rather bizarre rationalizations for the way they live and how others ought to be, especially when physical and emotional needs arise that don’t fit cleanly within their ideals.',
  ],
  sx: [
    'Sexual Ones seek to experience Essential Integrity in their sexual relationships and attraction displays. The idealism of Type One manifests here most acutely as attempting to be the best kind of romantic partner, to have the best partner, and to have an untouchable kind of chemistry. They’re not so much interested in appearances, though they certainly give it attention; instead, they aim to exemplify traits that make them exceptional and therefore desirable, and, in turn, they look for a partner who shares these qualities and with whom they can have the right kind of relationship.',
    'In contrast to the stereotype of the straight-laced One, Sexual Ones often have hobbies, interests, and careers that may seem out of bounds for a type that is typically perfectionistic. These interests often seem, on the surface, unrelated to attraction, but their “hook” is that they’re usually fascinating, adventurous, or creative, and performed to a high enough standard of excellence that it stands out. By seeming to be rooted in an ideal other than attraction, their attraction-displays also serve the additional purpose of giving the Sexual One’s ego “plausible deniability” that these activities are sought for a higher purpose than just procuring sexual attraction.',
    'Sexual Ones can have an infatuation for the ideal. They may unconsciously create conditions where they either keep a relationship with a potential partner from being consummated or they become obsessed with unobtainable lovers, believing that this person is “perfect” for them.',
    'Autonomy plays a central role in the Type One personality, so the judgment that they direct at themselves, at lovers, and the relationship as a whole unconsciously functions to reinforce separateness. If the partner is too X, Y, or Z to infuse themselves with, or the Sexual One judges themselves to be unworthy or not good enough for their partner, this may present emotional difficulties.',
    'Sexual Ones often have an ideal kind of partner in mind, but their bodies may betray an attraction to people that don’t accord with their ideals. They may seek out partners who hit every box on their checklist but are poor lovers, or vice-versa. This can pit a Sexual One against themself in a clash between standards and reality, and there may be an unconscious dynamic of being turned on by their own frustration toward their partner. In partnerships, Sexual Ones can become ruthlessly critical and controlling of their partners, as if getting a thrill from turning partners into improvement projects.',
  ],
  so: [
    'Social Ones are looking to experience Essential Integrity in relationships, causes, and vocation. Social Ones tend to have a great deal of awareness about what’s going on in the world at large. They want to understand their place in it and how they can meaningfully contribute to its betterment. People of this type tend to be reformers, social crusaders, and standard bearers. They have a sense of mission and purpose and wish to set an example of how to live from integrity.',
    'Their sensitivity to context makes Social Ones naturally adept at seeing both the potential in others as well as where others fail to live up to it. This often has them gravitate toward mentoring, teaching, guidance, coaching, or leadership positions where they can foster the growth of individuals. In the Social One, autonomy conflicts come into play as a desire to become attached to a particular social set while finding that group to be not quite up to their ideals. Thus, the relationships and connections they seek to foster are in need of improvement. This keeps the Social One both engaged and oriented toward particular dynamics and people, yet on the outside. By being critical of them, they remain autonomous and separate.',
    'Although their impulse to reform is well-meaning, as their ideals become more rigid and unrealistic, their judgments become more intense. Unconsciously, the imbalanced Social One is perpetually striving for moral superiority, which finds an uneasy tension with the desire for connection and the Social Instinct’s awareness of others’ states. Social Ones can play out chronic frustration and judgment of loved ones and groups as a way to remain both separate from them and attached through a negative affect. To keep up the identity, no matter how others actually are, the entranced Social One will have to find fault and come from a position of judgment and condemnation.',
    'The pathological Social One can become a zealot for their visions of how society should be, taking on an air of purifying the social climate. An identification with feeling right can prevent them from being willing to see how their ideals may not work out as imagined.',
  ],
});
types.set('2', {
  core: [
    'In Type Two, the Essential Quality of Love, the intimate, interconnectedness of the present collapses into the Passion of Pride, a lack of self-acceptance and an inflation of positive motivations. Therefore, Type Twos deny the extent of their neediness for fear of having selfish motivations and project their own neediness onto others. This sets up a dynamic of caring for others while relying on them to meet the Two’s needs as a sign of reciprocity for the Two’s support.',
  ],
  sp: [
    'Self-Preservation Twos are looking to experience the Essential Quality of love through attending to the well-being, comfort, and health of others. They are classic providers and have a strong sense of obligation and responsibility.',
    'Because of the Self-Preservation emphasis on the body and on practical results, these Twos are warm but don’t often have the gregariousness of other Twos. Especially if they have a low Social Drive, the way they show their love and support may not often be as “personal” or as “face to face” as Twos dominant in Social or Sexual. Their style of support tends to be practical, like financial support, some sort of skill in healing, or caretaking. Their dedication and drive can make for an incredible capacity for selflessness and giving care, especially in times of crisis or when people can feel there’s no one else to turn to. Yet this often means Self-Preservation Twos neglect their own self-care and run themselves ragged for other people with the unconscious expectation that others will be there in their own time of need. Time and energy not focusing on the benefit of others can create anxiety. They may withdraw or self-indulge in food or idle time to compensate for the care they feel they’re not getting. This gives the appearance of self-care without the actual care.',
    'In some cases, Self-Preservation Twos have been so caught up in performing a function for others or in occupying a caretaking role that they may not know how to relate to others without having something to offer. Despite all their helping, they may not have formed a bond on the personal levels they thought or wanted because it had all been contingent around a dynamic of offering support. This situation compounds the feeling of being uncared for, which their superego takes as a sign they’re not doing enough. In extreme cases, this can lead to the Self-Preservation Two essentially performing roles and tasks they’re not qualified for simply for the sake of being needed by others.',
    'Over time, a lack of adequate self-care paired with a Two’s difficulty in directly asking for what they need can create a pattern of resentment and entitlement. They jump into situations to provide support to others in the hopes of being cared for in return, but those who benefit from the support can become habituated to it without understanding the Two’s expectations for reciprocation or the amount of energy the Two is spending. Twos can then feel that their boundaries have been impinged on, occasionally culminating in eruptions of devastating anger.',
  ],
  sx: [
    'Sexual Twos long to find the Essential Quality of Love through their romantic relationships and attractions. Sexual Twos often have a coquettish persona, and they typically know how to turn up the intrigue and sexual tension while still retaining a “good” image.',
    'Sexual Twos often struggle with craving nearly constant attention from the object of their desire and have learned how to be attention-grabbing in order to keep it. This betrays an often deep-seated insecurity around their own genuine attractiveness and about their ability to maintain that attraction over a period of time. They might be physically beautiful but have severe insecurities that their personality is repellant, or they might simply worry that they themselves can’t keep attraction and passion intense enough, whether or not this is a real concern of their partner.',
    'When attracted to someone, Sexual Twos may try to force a relationship in a variety of ways. Even relatively balanced Sexual Twos have a difficult time not being in a relationship, so infatuation based on very little is a frequent occurrence. They may even talk themselves into being attracted to certain people in order to force the chemistry. The Sexual Drive combined with the Pride of Two often manifests as over-doing efforts to attract, allure, and occupy their partner’s attention while often not being real with themselves about the true state of their own attraction. They may have so much emotional reactivity around losing their partner’s interest that they may be unaware if they themselves have lost attraction to their partner instead.',
    'Sexual Twos who are imbalanced may throw themselves at any potential partner who reciprocates, or, conversely, at those whose attraction is most difficult to earn. This can lend itself to the Sexual Two choosing partners who aren’t up to their intellectual and emotional level, who take them for granted, or who reinforce a negative psychological status quo. When insecurity around desirability sets in, the Sexual Two can become invasive, both in terms of trying to receive sex and attention as reassurance, as well as acting out intense possessiveness, jealousy, and control. When unbalanced, Sexual Twos can engage in exaggerated displays of love, attraction, devotion, and simply assume that they are the best possible partner for their object of desire.',
  ],
  so: [
    'Social Twos seek to experience Essential Love in their relationships, vocation, and their sense of belonging. Social Twos are typically deeply involved with people and have a great deal of energy for relationships. Because of this, they have wide social networks, typically serving as a central axis within their milieu. Social Twos have deep fears of exclusion, both in interpersonal relationships and in their social context. Therefore, they may acquire specialized relational skills in order to have something to offer to those who make the effort to connect with them. They are also likely to insert themselves into other people’s relationships and affairs as necessary connective tissue and into conflicts as mediators.',
    'Pride can make it hard for Social Twos to see the extent of their social positioning and interpersonal meddling. Because of the Social Two’s emphasis on positive intentions and loving feelings, they may fail to see themselves as socially ambitious. Yet this very lack of acknowledgment is often why people sometimes pull away, keep  distance, or end relationships with them.',
    'Further complicating the matter is that, in not wanting to expose the elements of themselves that the superego deems selfish or unlovable, a Social Two will be unreceptive to genuine help and support. The hierarchy-making element of the Social Drive can express itself here as creating an unconscious dynamic of positioning oneself “above” others, as one who bestows support while others must always be on the receiving end. Others may feel that the Social Two will not allow them to be on equal footing, making the real connection and intimacy Social Twos crave impossible. Neurotic Social Twos have an extremely difficult time being alone or not being involved in other people’s aims and affairs.',
  ],
});

types.set('3', {
  core: [
    'In Type Three, the Essential Quality of Value, the precious, actualized quality of the present moment collapses into the Passion of Vanity, self-deception and the over-valuation of the ego. Therefore, Type Threes seek to craft a persona that will have the greatest ability to obtain the most desirable instinctual resources.',
  ],
  sp: [
    'Self-Preservation Threes strive to experience Essential Value in their accomplishments, lifestyle, and careers. They tend to emphasize efficiency, tangible results, and mastery of specific skills more than Sexual and Social Threes. Self-Preservation Threes are typically very driven and can be quite competitive, although contrary to some stereotypes not every Self-Preservation Three is wealthy and materially accomplished, as their values may lie elsewhere. A Self-Preservation Three may opt for a humble lifestyle, yet, they may be the most experienced healer in their community or a Yoga teacher with the most training and credentials to show for it.',
    'As values and capacities change over the course of a lifetime, however, Self-Preservation Threes can struggle with finding a path forward in life that results from their authentic values rather than something they’re good at. They may find themselves running off an “inner program” that they adopted at an extremely young age and therefore find themselves struggling to feel relevant when outer circumstances and cultural views of value change. Likewise, they may avoid experimenting or trying out things that they think they won’t be naturally good at, limiting their options and overall approach to life early on. Their efficiency and achievement can lend itself to a kind of momentum toward goals that can sweep them up without their heart really being in it. They may find themselves following a path that is not aligned with their deeper values and have a hard time finding a path in life that isn’t based on their forward-moving energy.',
    'Self-Preservation Threes are prone to workaholism, running themselves into exhaustion and achieving without awareness or concern of the larger context or impact on others. Even though Self-Preservation is their Dominant Instinct, people of this type can over-do exercise, physical performance, and work at severe cost to their overall health. These activities can become another means of achievement, divorced from their original aim of enhancing the body’s well-being.',
  ],
  sx: [
    'Sexual Threes seek to experience Essential Value through their desirability and the magnetism of their attraction displays. Sexual Threes want to be the most magnetic person in the room. They feed off of generating intrigue, mystique, and even controversy, and they aren’t much concerned with being liked or pursuing practical achievements. Competition in Sexual Threes revolves around being the most attractive and having the most captivating sexual display, and they’re most likely to have cultivated a striking personal flavor meant to stand apart from others.',
    'Competition and ambition can also play out as making it big in fields where they can signal their sexual value, such as modeling or performing. “Failure” is extremely painful for Threes as a whole, but for Sexual Threes, failure is defined as a failure to attract, incite interest, or to keep the focus of their romantic partner. Sexual Threes will “pull out all the stops” to win a specific partner and will often adapt their personal style, preferences, and image into what they believe is most desirable. As a result, they often struggle to allow their partner to discover who they are beneath the display. When unbalanced and fearful, this can lead to Sexual Threes rejecting partners when an intimate bond forms, disappearing behind their sexual “performance,” or conversely, becoming possessive and controlling, suspecting sexual rivalry at every turn. Entranced Sexual Threes can isolate their partner from friends and other people or turn run-of-the-mill social engagements into “battles” of fending off rivals and projecting their energy all over the place.',
    'Unhealthy Sexual Threes can view themselves and their partners as “prizes” in that having partners who are attractive and desirable becomes a statement on their own desirability. Therefore, imbalanced Sexual Threes may enter into relationships that support their narcissistic self-image or relationships that are toxic, wherein the partner’s lack of appreciation of the Three beyond their sexual display reinforces a further division between their perona and their authentic self.',
  ],
  so: [
    'Social Threes look to experience Essential Value in their relationships and vocation, particularly with the people with whom they experience belonging. Many Social Threes are highly accomplished and talented, but much of their drive stems from wanting to inspire others through their example. It’s important for Social Threes to feel they are seen as exemplars of whatever may be valuable within their social context, and they especially want to be seen as special to loved ones on a personal level. Social Threes don’t wish to conform to their social milieu so much as they wish to be a force within it, the one who sets new standards and raises the bar higher for the culture they’re in.',
    'They can be so skillful at progressing toward their aims that they may catch themselves pursuing a path that they didn’t have that much interest in. Often, Social Threes get caught playing many different roles for many different people and are unable to inwardly locate themselves apart from the roles they’re called to play. When a different persona is called for, Social Threes often become the exemplar of it. Many Social Threes fall into the trap of blurring their private life with their professional persona, living as if they have to always be “on” in promoting themselves like a personal brand. Private experiences may be undertaken with a public audience in mind, which can drive intimacy from relationships. The need to be seen as desirable and special can lead to Social Threes wanting to position themselves in socially exclusive circles, presenting an aloofness which may run up against their desire for personal connection and leaving Social Threes feeling alone and insecure despite whatever prestige they’ve acquired.',
    'The ambitiousness of the Three personality can turn the desire for belonging into a motivation to constantly expand their influence, and they may begin to view others as personal challenges of whom they can win over and how quickly. Social climbing and vying for status, recognition, and exclusivity can replace any real connection with themselves and they can begin to act in ways that are incongruent with their heart’s authentic wishes in order to get ahead socially.',
  ],
});
types.set('4', {
  core: [
    'In Type Four, the Essential Quality of Depth, the mysterious, bottomless quality of the present, collapses into Envy, chronic disappointment and a reaction to the inadequacy of the personality. Fours seek instinctual resources which they hope can meet their longing for depth while reacting to the inability of resources to provide the Depth they seek.',
  ],
  sp: [
    'Self-Preservation Fours strive to experience Essential Depth through their lifestyle, creativity, and self-expression. They usually require periodic bouts of solitude to be immersed in their creative projects, but they struggle with finding a lifestyle that is congruent with their needs and inner experience.',
    'The Self-Preservation Instinct results in an insular, highly sensual, and tactile Type Four. They’re especially sensitive to matters of aesthetics and ambiance, and their preferences of environment and home are reflections of their idiosyncratic personalities, having more to do with emotional resonance than comfort.',
    'Self-Preservation Fours are looking for their home, work, and overall lifestyle to be as close an expression of and congruent with their subjective experiences as possible. Their lifestyle and environment should be a container for their self-discovery, aesthetically evocative of what draws them inward while being sheltered from outside intrusion. In this type, Envy lends itself both to a struggle with feeling functional and capable and, more centrally, to a frustration that the overall picture of one’s lifestyle doesn’t accord with an idealized self-image. They can become so myopically devoted to forging a personalized and individualistic path that they fail to develop practical and interpersonal skills or make certain compromises which may help them achieve their aim.',
    'When imbalanced, Self-Preservation Fours can “paint themselves into a corner,” limiting their possibilities and opportunities for growth by rejecting all that doesn’t accord with their self-image and abhorring anything that limits their creativity. People of this type can have an indulgent streak, especially when it comes to spending beyond their means to acquire objects of beauty or to pursue situations, travels, or opportunities that speak to them. This can be a strength—a devotion to feed their inner life—or a way they shoot themselves in the foot. They are often tenuously balancing between financial security and collapse. Emotional states and self-comforting are modified through indulgence in excessive eating, drinking, sex, and carelessness. Unhealthy Self-Preservation Fours are prone to masochistically acting out against themselves physically, by going without food, sleeping in bizarre places, and even self-injury.',
  ],
  sx: [
    'Sexual Fours long to experience Essential Depth in their relationships, creativity, and intense experiences. They are prone to demonstrating their creativity and depth as a means to entice and sexually attract, and they can fetishize emotional, intellectual, or spiritual depth, imbuing it with an erotic mystique and deep contempt for the mundane.',
    'Both Type Four and the Sexual Drive emphasize characteristics that distinguish oneself from others; compounded, Sexual Fours cultivate identities that are hyper-specific and elaborate. This hyper-specificity aims to be very attractive to a few and to repel those deemed too “banal” to appreciate their unique flavor. They want to be uninhibited in pursuing attractions, so they’re typically resistant to structure, confining jobs, and adherence to routines. There is often a struggle to sustain themselves practically.',
    'Envy lends itself to chronic doubts about attractiveness and the ability to keep those they wish to attract interested in them. Hypersensitivity to their partner’s perceived level of attraction generates great distress if there are any lulls or mellow periods, so Sexual Fours tend to be sexually competitive—they feel they can’t be magnetic enough, and therefore are always trying to shore up their display of talents while never feeling adequate. They may feel the need to be the greatest love of the partner they’re with or, at least, the most impactful and unique one. Envy also creates an excessive focus on perceived personal defects, which a Four will inevitably find, that disqualifies them from having and keeping the person they want.',
    'This can lend to Sexual Fours testing their partners and desired objects in various ways: possessiveness, suspicion, or causing fights to feel “entangled.” They’re prone to acting out stormy swings between idealization and disillusionment, extremes of love and hatred. Sexual Fours can play out a pattern of frustration with their loved ones, wanting their loved ones to be everything for them and rejecting them when their partner is unable to meet unrealistically high expectations.',
    'Disintegrating Sexual Fours are prone to self-harm, emotional abusiveness, and physical violence toward themselves and their partners, acting out intense hatred and possessiveness toward their partner and adopting a reckless, “burn it all down” approach.',
  ],
  so: [
    'Social Fours are looking to experience Essential Depth in their relationships, creative offerings, and social roles. Social Fours combine an appreciation for depth and authenticity with an interest in other people, lending to deeply personal self-revelation in their artwork, interests, and general self-expression. These Fours can adapt themselves to Social situations with greater ease than other Fours, yet they still need to maintain a sense of being different from others in some remarkable way.',
    'The Four’s desire to be a unique individual comes into tension with the Social Drive’s need to be available for connection, so in Social Four, there’s a special effort to embody and share a deeper view of life in a way that is comprehensible and useful to others without compromising their personal vision. Whereas the Social Drive generally wants to find “common ground” with others, Social Fours crave connection while feeling uneasy about that which is “common,” so they seek to cultivate extraordinary connections with a select few. People of this type are usually not “people persons.” They are likely to fantasize that a social group, friend, or lover who will see who they “really” are is elsewhere, often ignoring the love and acceptance that’s already present for them in the relationships at hand.',
    'Social Fours feel that their differences and unique perspective is a strength, one they long to be recognized for, and at the same time, Envy often brings their inadequacies into extreme focus, making them self-conscious and feeling unable to connect, comparing themselves to how they could be if only they had some other characteristic or quality. They can adopt an exotic, mysterious, or sophisticated persona. They can identify with being an outsider and appreciate the mystique that affords while also longing to be among a more elite, studied, or chosen circle.',
    'When feeling slighted or unacknowledged, Social Fours are prone to adopt an arrogant, elite attitude. Distressed Social Fours can make dramatic public displays of their anger, with accusations of betrayal and cutting criticisms. They can easily feel humiliated, leading to exaggerated motivations for revenge and seriously undermining others for perceived slights, and they can become so focused on their own pain as a justification for their behavior that they fail to see the extent of their impact. desire.',
  ],
});

types.set('5', {
  core: [
    'In Type Five, the Essential Quality of Insight—the clear, revealed quality of presence—collapses into the passion of Avarice, withholding oneself from contact and filtering experience through conceptualizations. Type Five seeks instinctual resources that support a state of concentration and discovery without requiring too much from them personally.',
  ],
  sp: [
    'Self-Preservation Fives are seeking the Essential Quality of Insight through their lifestyle and interests. They have a deep capacity for concentration and are typically insightful, quirky, and intensely specialized in certain areas of expertise. Self-Preservation Fives are looking to leverage their skills—intellectual, creative, or otherwise—into earning a sustainable living that allows them to pursue their passions and interests without being controlled or too at the behest of other people’s demands and agendas. Many Self-Preservation Fives do this quite literally by living in their studio, or making their living space into an office, laboratory, or library, for example.',
    'Alone, unstructured time is a major priority for this type, as they are easily drained by the demands of others and wish to have uninterrupted focus. They often have careers or jobs that require minimal ongoing interaction with others or have otherwise arranged their life so as to have plenty of time to themselves. Whereas most people seek to keep their work within a boundary, limiting time and energy In order to have freedom in their personal lives, Self-Preservation Fives keep their “personal life” quite narrow so they can be free to focus most of their energy on their interests. Self-Preservation Fives’ interest is their life’s central focus, while they can compartmentalize other demands of living or treat them as secondary.',
    'This type constantly struggles to have the energy and attention for tackling life’s necessities. They can become overwhelmed by the demand of having to attend to their own needs, and as such, retreat into living “around” those needs instead of addressing them, like inadequate care of hygiene or letting their home fall into disrepair. They may also leave the cultivation of interpersonal relationships up to imagination. This can also create unprocessed anxiety, further making self-regulation challenging.',
    'Fear of depletion can turn into a literal fear that outside forces are taking something from them, often leading to obsessive fixations on paranoid ideas. Despite the withdrawn and often disconnected character of the Five, they can be quite aggressive, demanding, and controlling when they feel threatened while simultaneously unwilling to fully take responsibility for their aggression.',
  ],
  sx: [
    'Sexual Fives look to experience Essential Insight in their romantic relationships, chemistry, and interests. When Sexual Fives encounter someone they share chemistry with, they have enormous energy for hashing out ideas and probing uncharted conceptual vistas together, as if the energy of the fascination element of attraction will itself give birth to something totally new. While all Fives enjoy diving deeply into subjects that interest them, the Sexual Five uses their interests and knowledge to elicit attraction by advertising what a rich, interesting, and even transgressive inner life they have.',
    'As much as Sexual Fives may crave attraction, chemistry, and sexual relationships, Avarice means that they also have fear that they’re unable to provide enough emotional connection, physical adequacy, and practical support for their partner or desired beloved. Sexual Fives often believe it requires more “juice” than they have to keep the intensity of the chemistry going, so they can withdraw or try to create limits on their partners’ expectations of them. Sexual Fives anticipate the demands of a relationship before such demands are made, and thus, they’re often wrong about what the requirements will be but exhaust themselves by the mere anticipation of them.',
    'In craving intense chemistry, they are also prone to put certain conditions or blinders on the relationship so they can continue to have the chemistry they seek without the burden or distraction of the facets of a relationship that are normal for most people. This is consistent with Five’s contradictory feelings with regard to instinctual resources, both wanting them and trying to minimize or manage the conditions within which these needs are met. This can lead to their partner feeling resentment over being so much of the dynamic having to be on the Sexual Five’s terms.',
    'Avarice lends all Fives to mentally abstract themselves from their experience, and in the case of this type, Sexual Fives can approach the erotic conceptually. Therefore their fascinations are often organized around the symbolic and veiled, and typically, the pursuit of their interests is tied in with a sense of self-revision. Sex itself is a major need for Sexual Five, but it can come with highly specific conditions, rituals, or unconventional expressions of sexuality. These can be both to psychologically prepare them to get out of their heads as well as symbolize a kind of merging of their conceptual world and the practical world, Sexual Fives can be consumed with bizarre ideas not founded in reality, and they may develop erotically-charged obsessions with certain people and concepts.',
  ],
  so: [
    'Social Fives are looking to experience the Essential quality of Insight in and through their relationships, their interests, and their contributions. They have a kind of Promethean calling, whereby the want to offer wisdom, insight, creativity, and understanding to loved ones and the world at large—to peer “behind the veil” in order to bring illumination. At the same time, they can be fearful of being overwhelmed by the interpersonal burdens that come from participation with others.',
    'Social Fives are drawn to fields, groups, and institutions that hold the promise of engaging with fascinating people who are at the top of their game intellectually, creatively, or otherwise. Contrary to the stereotype that Fives only value knowledge, Social Fives enjoy being stimulated and impacted by all kinds of people, and they respect mastery above all. Through their capacity for insight and new understandings, the Social Five hopes to claim their place or niche and solidify their interpersonal and social value. They’re excited by the feeling of being a part of a tradition or specialized class, but these special groups can also be a way Social Fives seek to sequester themselves away from the messy or practical elements of life they feel unprepared to face.',
    'Avarice can be expressed as a tension of wanting both to deeply belong as well as to separate themselves, usually through social distinction, such as being the expert or even presenting themselves as uniquely gifted or insightful. This sense of superiority is a double-edged sword, as they believe being the key expert will assure them of the social value and belonging they desire while also creating separation and a lack of interpersonal connection. This tension can lead to a great deal of alienation: belonging is not sensed directly, but rather abstracted and conceptualized, leading to loneliness and a sense of isolation as the Social Five doubts their value and the niche they’ve carved out.',
    'Social Five can express Avarice as wanting to contribute their gifts and creativity meaningfully, but not feeling equipped to handle the responsibilities that may come from being in leadership. As Social Fives become more unbalanced, they feel their contributions are underappreciated and their genius under-recognized. They may become both angry and frightened of the masses who can’t appreciate them, making public displays of their superiority that almost always backfire. Deeply imbalanced Social Fives may entertain delusions of their social specialness and significance and may imagine others conspiring against them.',
  ],
});

types.set('6', {
  core: [
    'In Type Six, the Essential Quality of Truth, the quality of the present moment that is experienced as real and foundational collapses into the Passion of Fear, a lack of orientation and doubt. Therefore, Type Sixes are seeking an assured means of acquiring instinctual resources that will provide a stability and solidity that the personality lacks.',
  ],
  sp: [
    'Self-Preservation Sixes long to experience Essential Truth in their lifestyle, path of personal growth, and resources. The devotedness and reliability of the Six meets the perseverance of the Self-Preservation Drive, lending itself to a deep awareness of how the things they value grow and are sustained. Much like their neighbor, Type Five, Sixes are extremely observant, but in contrast to Five’s narrow focus, Sixes’ have a broader quality awareness that is attentive to how parts relate to the whole, as in how a tree can only grow relative to the integrity of its roots. Awake Self-Preservation Sixes bring together this awareness with an inherent inner resourcefulness that lends to confident self-possession and meeting challenges with acceptance and fortitude.',
    'This type is often adept at discerning patterns and keeping things “on track” toward their intended results. They are the most practical Sixes and tend to be exceptionally mindful, giving care and attention to the details that others overlook. While some Self-Preservation Sixes have a great deal of anxiety around their safety and well-being, it is typically balanced with having an intrepid or adventurous side.',
    'Self-Preservation Sixes are acutely aware of chaos and the absurdities of life. To manage anxiety, they create or turn to systems that help keep all bases covered. Without ongoing attention to life’s necessities, they fear things may collapse into entropy. Often, they rely on complex means of organizing their attention, like keeping to well-structured schedules. This can lend itself to a need for routine, predictability, and an over-emphasis on procedures and a lack of ambiguity.',
    'When they feel unsupported, Sixes will look for something reliable on which to model their path through life on, but in doing so, they may fail to tap into all their creativity or potential. This may lead them to keep their world small and anxiety-ridden. They can become attached to a job, a situation, or a life path that isn’t personally rewarding but provides some direction and clarity, and they will end up sticking with something even after it’s no longer to their benefit. As they become more imbalanced, they begin to feel that keeping things together is left solely up to them. They can live life from their minds, trying to regulate and create structure to the flow of life, which can lead to an attachment to ideas over directly entering into the unpredictability of life. They are prone to spending a great deal of their energy living in anticipation of imagined disasters that may never arrive.',
  ],
  sx: [
    'Sexual Sixes seek to experience Essential Truth through chemistry and in their romantic relationships. The contradictory nature of Six is expressed in this type as a bold and provocative attitude paired with vulnerability and uncertainty about their desirability. They tend to be unpredictable and edgy, and yet very charming and endearing. Freedom of expression is often paired with the Sexual Six’s need to check in on whether their actions undermine or enhance their appeal. A need for certainty in the fluctuating arena of attraction and chemistry speaks to the basic conflict within this type. Sexual Sixes are looking for chemistry they can rely on to be sustainable and energizing. They tend to project swagger with a tough or dramatic “hard to handle” attitude, yet they often display a great deal of unexpected vulnerability, sensitivity, and sentimentality, needing a great deal of assurance that their partnership is secure and that they’re still enticing and beautiful.',
    'Despite bouts of confidence, insecurity arises on whether or not their partner will remain faithful and interested in them when potential rivals are around. They may start fights with perceived sexual rivals who, in reality, may have zero interest in their partner. It may be difficult for Sexual Sixes to fully relax around their partner, which can mean being “on” too much, needing to impress or seduce in order to capture attention.',
    'It’s not that all Sexual Sixes are interested in long-term monogamy, but when they do find a partner they wish to be exclusive with, they can become possessive and competitive in trying to keep them because of a basic lack of trust in the elements of attraction that they may not see or have control over. Some Sexual Sixes can test their partners to see if they will leave them. Sexual Sixes may also use one relationship after another to prove to themselves they can still attract whomever they please, or they may become attached to a partner who is a “sure thing” in desiring them.',
    'As Sexual Sixes become imbalanced, they may lash out at their loved ones and entertain paranoid fantasies about abandonment or betrayal. They may even gravitate toward partners who they have a sense will betray them, so when it does happen, it reinforces an identity structure of not being able to trust or believe in anyone. Deeply unhealthy Sexual Sixes can be aggressive and controlling toward their partner, using them as an emotional punching bag to discharge their anxiety and frustrations. Unhealthy Sexual Sixes who are single might not respect boundaries in pursuing potential partners and sexual interests.',
  ],
  so: [
    'Social Sixes want to experience Essential Truth in their relationships, contributions, and causes. They seek meaningful connections with others and are as interested in individuals as they are with the underlying reasons, values, and commonalities that keep bonds enduring and sustainable. This type has a deep longing to feel a solid sense of belonging with others. As friendly as Social Sixes can be on the surface, on the inside they may harbor a deep cynicism about other people’s reliability, integrity, and dependability. Many Social Sixes are charming, funny, and kind, but they also have a sharp, critical side with which they use to probe others’ authenticity and character. This type has strong expectations of friendships and relational dynamics that aren’t always explicitly communicated, so they can feel betrayed or let down by people who can’t meet these expectations.',
    "People of this type tend to get caught up in beliefs and ideologies that serve as umbrellas for people coming together, but they can let their devotion to these ideological tentpoles run away to the point of actually undermining the very interpersonal connections they wish to foster—for instance, in the case where adherence to a political cause ends up alienating the people it's supposed to benefit. Social Sixes can begin to believe their belonging is contingent on maintaining specific relational structures, of which they see themselves as a guardian, so this can escalate to larger social structures, like a political ideology, familial loyalty, or religion, taking precedence over the interpersonal connections it was there to support in the first place. In other words, the idea overtakes reality.",
    'As they become more imbalanced, they can struggle in distinguishing their own independent agenda and identity, resulting in a vacillation between adherence to an authority or compulsive rebellion; alternatively, they may hold a black or white view of other people’s moral character. They may often replace one authority for another as if choosing a new inner authority figure represented a self-directed choice. As Social Sixes become more imbalanced, they can pick fights in trying to test interpersonal loyalty and get at loved ones’ “true feelings” for them. Their bright minds can become co-opted by the impulse to justify their ideological frameworks at the expense of open inquiry, complete with supplying effective arguments, “evidence,” and seemingly coherent justifications. Deeply unhealthy Social Sixes can be bent on punishing real or imagined wrong-doing and can act obsessively to purge “bad” beliefs or people from their social group.',
  ],
});

types.set('7', {
  core: [
    'In Type Seven, the Essential Quality of Freedom, the independent, liberating quality of the moment collapses into the Passion of Gluttony, insatiability and distractibility. Type Seven is seeking to sample a broad range of instinctual resources in the hopes of finding fulfillment or distraction, but this only perpetuates frustration and feelings of deprivation.',
  ],
  sp: [
    'Self-Preservation Sevens seek Essential Freedom in their lifestyle through experiences and sensual pleasure. They are the most practical and experience-oriented Sevens. They typically have a natural talent for synthesizing skills and creating businesses, art, and adventures, and they might combine these elements into something unexpected, yet useful and interesting. Self-Preservation Sevens find ways to arrange their lifestyle so they can pursue the kinds of experiences, subjects, and interests they love while also ensuring some degree of well-being and material security. Where and how they live is viewed as the nexus to what opportunities and experiences will be available to them. Some Self-Preservation Sevens have multiple projects and money-making endeavors, and they love to travel and have intense experiences. People of this type have a great deal of resilience in the face of setbacks and upheavals. They also have a gift for extending this attitude to friends and loved ones, “sharing the wealth” by means of material support or opening up opportunities for others.',
    'elf-Preservation Sevens express gluttony for resources and experiences that they believe provide physical well-being, an interesting life, and sensual pleasure. Consumption is a major Self-Preservation Seven theme—big expensive meals in fancy restaurants, big shopping excursions, collections, interests in upscale and luxury items are all possible examples. Or, they may live humbly but display a voraciousness in reading, passion for art or film, or prodigious creative output.',
    'Self-Preservation Sevens struggle to know what conditions to agree to, what skills to develop, and what roots to put down in order to foster the kind of life they want to lead. Some Self-Preservation Sevens can feel crushed by a demand to have a life trajectory established by a certain age or by the expectations family may have around what kind of lifestyle they choose.',
    'In Self-Preservation Sevens, anxiety around the limitations and state of the body creates a kind of impatience with the body and with healing, which exacerbates whatever physical and psychological issues are at play. Under stress, they adopt a predatory “me first” entitlement that can be overt in their attitude toward others or played behind the scenes by “borrowing” what they want or scheming for what they feel they are owed or what they think others won’t miss. They may also overestimate their energy and become workaholics in an effort to keep up stimulation and to prevent feeling overwhelmed by anxiety. Many unhealthy Self-Preservation Sevens may indulge in substance abuse, excessive partying, and reckless physical risk-taking, trying to escape crushing inner feelings of deprivation and grief.',
  ],
  sx: [
    'Sexual Sevens want to experience Essential Freedom in chemistry, their fascinations, and their romantic partnerships. The high energy of Type Seven paired with the attraction-seeking, boundary-pushing Sexual Drive produces colorful characters who have a willingness to drop whatever they’re doing in pursuit of something that has captivated them. The object of desire represents a doorway to a new world and an entry into experiences they couldn’t have anticipated.',
    'There’s a sense that every partner, every romance, and every turn in the evolution of a long-term partnership is a new discovery. They can have a gluttony for arousal. Much of their talent, charm, and success comes from this capacity, but they can jump completely into one project or person, and then the next and the next; the consequence is that their life can take on a zig-zag pattern. In seeking fascinating people and experiences, Sexual Sevens want to be fascinating as well. Yet their tendency to be stretched thin may lead to having many interests but not a lot of proficiency in any one skill nor any particular direction in life, fueling an insecurity they may compensate for by resorting to being outrageous or provocative instead of well-rounded.',
    'As a type based in the Intellectual Center, all Sevens experience difficulty being in contact with a quality of inner knowing and discernment. When personality co-opts the Sexual Drive, it interferes with the natural intelligence and discrimination of attraction and chemistry, becoming overridden by intense mental excitation, a need for stimulation and seeing people through a veil of imagination. It can seem almost as if others become characters through the lens of a fairy tale or story. Therefore, a great deal of the basis for attraction of Sexual Sevens is the symbolic potential that the person and their relationship may open up. The obstruction of imagination over one’s experience can also easily turn into a pattern of chasing “peaks.”',
    'Imbalanced Sexual Sevens will hardly allow for a situation to unfold on its own, and instead will goad things along with provocation to up the ante or add something to the experience. When this happens, the natural transgressive and provocative impulses of the Sexual Drive become intensified by mental activity toward exaggerated exhibitionism and fascination with the perverse. This can both stave off the possibility of sincerity and intimacy and undermine their attractiveness.',
  ],
  so: [
    'Social Sevens are looking to experience Essential Freedom in their relationships and vocation. For this type, the possibility and variety of life is at its richest when shared. Social Sevens have a strong sense of purpose and a profound desire to meaningfully leave a positive impact on other people. They love making genuine connections, going on adventures with companions, and are generally able to find something worth appreciating in most people.',
    'While Seven and the Social Instinct, taken together, may evoke a picture of the buoyant social butterfly, not all Social Sevens are so extroverted. They tend to have extended networks of friends but have a tight inner circle of enduring connections. Even so, there’s a persistent sense of being called to be part of a larger world or bigger conversation and often a call to genuinely contribute to the betterment of others. Because of this, they are prone to being giving and self-sacrificing, often giving up opportunities, freedom, and self-interest for the sake of others.',
    'One of the major difficulties that Social Sevens struggle with is not knowing where to invest their energy and time, so Gluttony compensates for this lack of real knowing by trying to pursue nearly every option they find even a little bit interesting. It’s hard for them to settle on where to develop their gifts and contributions. Unconsciously, there’s a belief that finding the right kind of relationships and the right kind of orientation, role, or calling will unlock the meaning they’re seeking, yet the fear of missing out on what that calling is, or where that key to unlocking potential lies. Adding to this difficulty, Social Sevens tend to be able to see something positive and interesting in nearly every path, option, and person. It can also lead to a lack of discrimination of who and where to give energy to, resulting in a frustrating feeling that it’s nearly impossible to make the “inroads” the Social Seven seeks or to figure out what to devote themselves to.',
    'Under stress, Type Sevens have an unconscious habit of setting themselves up for disappointment by overlooking negativity or making agreements without fully considering the consequences of doing so. They may agree to take on responsibilities toward many people or organizations until they feel bogged down and resentful, searching for a quick way out.',
    'As Social Sevens become overtaken with anxiety, they can be ungrounded, unreliable, and out of control while retaining a charming façade, so others can easily be swept up into the Social Seven’s impulse to escalate situations. In trying to enhance the social atmosphere through outrageousness, imbalanced Social Sevens are prone to escalation, burnout, and putting themselves at risk through self-neglect and recklessness. The focus on other people flips to self-absorption and hedonism, using other people and betraying their trust.',
  ],
});

export const EnneaDescriptionModel = {
  sourceTitle: sourceTitle,
  source: source,
  buyBook: buyBook,
  types: types,
};
